### ISSUE TITLE
There is no "Profile by line" button on version 5

### ISSUE THREAD

**Issue by PasaOpasen** [spyder-ide/spyder.line_profiler#57] opened 2022-02-26 19:54 UTC
I successfully installed spyder-line-profiler via Anaconda, but there is no "Profile by line" button in Run part

```
* Spyder version: 5.1.5 None
* Python version: 3.8.5 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.13.0-30-generic
```

I tried to use this plugin in Windows10 too, but it never worked with Spyder 5

**Comment by dalthviz** [comment] 2022-02-28 15:19
Hi @PasaOpasen thank you for the feedback. I'm closing this as a duplicate of #52 which should be fixed once we merge #56 and available with a new release (most probably 0.3.0).

To use this plugin for the moment you will need to either use Spyder 4.2.5 or give #56 a try locally by, for example, installing the plugin via pip from the contributor fork and branch (if you want to do this I would suggest you to create a new environtment to prevent any issue with your current setup).

Hope the info above clarifies a little bit the state of things :)

**Closed as completed by dalthviz** 2022-02-28 15:19 UTC
Labels: reso:duplicate
