### ISSUE TITLE
Find correct python install

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder.line_profiler#5] opened 2016-05-03 14:53 UTC
Right now the first executable on the path is taken, while it should probably be smarter by using the python version configured in spyder.

Initially reported in https://github.com/Nodd/spyder_line_profiler/issues/28

**Comment by jitseniesen** [comment] 2022-08-09 12:39
I am closing this as a duplicate in favour of #67 because I think the issue is better described there.

**Closed as not planned** 2022-08-09 12:39 UTC
